version: "3.8"  # optional since v1.27.0
services:
  nodeserver:
    build:
      context: .
      image: apitoken/watsonstt
    ports:
      - "30000:30000"

  web:
    build:
      context: ./nginx
    # image: apitoken/watsonstt
    environment:
      - TZ=Asia/Hong_Kong
      - VIRTUAL_HOST=token.10botics.com
      - LETSENCRYPT_HOST=token.10botics.com
      - PORT=80
    # volumes:
    #   - "./default.conf:/etc/nginx/conf.d/default.conf"
networks:
  default:
    external:
      name: docker05

